export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const ADD_PRODUCT_PRICE_HISTORY = "ADD_PRODUCT_PRICE_HISTORY";
export const UPDATE_PRODUCT_PRICE_HISTORY = "UPDATE_PRODUCT_PRICE_HISTORY";
export const DELETE_PRODUCT_PRICE_HISTORY = "DELETE_PRODUCT_PRICE_HISTORY";
export const CLEAR_PRODUCTS_PRICE_HISTORY = "CLEAR_PRODUCTS_PRICE_HISTORY";
